name: TypeScript Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build with TypeScript
        uses: microsoft/typescript@v4
        with:
          args: '--project . --noEmit --strict'

      - name: Check for errors
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git status
            exit 1
          fi
